name       : telepathy-rakia
version    : 0.8.0
release    : 1
source     :
    - http://telepathy.freedesktop.org/releases/telepathy-rakia/telepathy-rakia-0.8.0.tar.gz : 1baebcd391e0ba199f2f6faa2c99b53ba03e732e80290827de5e42889473bda1
license    : LGPL-2.1
component  : network.im
summary    : SIP connection manager based around the Sofia-SIP library
description: |
    SIP connection manager based around the Sofia-SIP library
builddeps  :
    - pkgconfig(sofia-sip-ua-glib)
    - pkgconfig(telepathy-glib)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
